#define CART_START 0x0000
#define CART_END 0x7FFF

#define VIDEO_RAM_START 0x8000
#define VIDEO_RAM_END 0x9FFF

#define SWITCH_RAM_START 0xA000
#define SWITCH_RAM_END 0xBFFF

#define INTERNAL_RAM_START 0xC000
#define INTERNAL_RAM_END 0xDFFF

#define ECHO_INTERNAL_RAM_START 0xE000
#define ECHO_INTERNAL_RAM_END 0xFDFF

#define OAM_START 0xFE00
#define OAM_END 0xFE9F

#define EMPTY_START 0xFEA0
#define EMPTY_END 0xFEFF

#define IO_PORT_START 0xFF00
#define IO_PORT_END 0xFF4B

#define EMPTY_NO_IO_START 0xFF4C
#define EMPTY_NO_IO_END 0xFF7F

#define INTERNAL_HIGH_RAM_START 0xFF80
#define INTERNAL_HIGH_RAM_END 0xFFFE
